# Generated by Django 4.1.7 on 2023-03-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_district_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
