# Generated by Django 4.1.7 on 2023-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, choices=[('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
