# Generated by Django 4.1.7 on 2023-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, choices=[('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
