# Generated by Django 4.1.7 on 2023-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
    ]
