# Generated by Django 4.1.7 on 2023-03-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_variant_remove_product_color_delete_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
