# Generated by Django 4.1.7 on 2023-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_size_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Orange', 'Orange')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
