# Generated by Django 4.1.7 on 2023-03-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_cartitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
