# Generated by Django 4.1.7 on 2023-03-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_cartitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
