# Generated by Django 4.1.7 on 2023-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
