# Generated by Django 4.1.7 on 2023-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_order_delivery_expected_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
