# Generated by Django 4.1.7 on 2023-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_order_order_no_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
