# Generated by Django 4.1.7 on 2023-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
