# Generated by Django 4.1.7 on 2023-03-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_address_district'),
        ('shop', '0037_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_coupon_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
