# Generated by Django 4.1.7 on 2023-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_coupon_used',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
