# Generated by Django 4.1.7 on 2023-04-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
